version: "3"
services:
  db:
    container_name: db
    build:
      context: db
      dockerfile: Dockerfile
    volumes:
      - ./db/mydatabase.sql:/tmp/mydatabase.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "mydatabase"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - kubernetes_app_practice
  back:
    container_name: back
    build:
      context: fullserver
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - kubernetes_app_practice

networks:
  kubernetes_app_practice: